"""multimodal verification domain

Revision ID: 83b3e835848b
Revises: 84ad8293d066
Create Date: 2026-09-02 08:16:27.809425
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '83b3e835848b'
down_revision = '84ad8293d066'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_profiles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('signals', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_profiles_host'), ['host'], unique=True)

    op.create_table('verification_jobs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_kind', sa.String(length=32), nullable=False),
    sa.Column('input_label', sa.String(length=512), nullable=True),
    sa.Column('submitted_by', sa.String(length=128), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_vjobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('analyzed_contents',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('publisher', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_url', sa.String(length=2048), nullable=True),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('redirect_chain', sa.Text(), nullable=True),
    sa.Column('og_metadata', sa.Text(), nullable=True),
    sa.Column('fetch_status', sa.String(length=32), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('text_stats', sa.Text(), nullable=True),
    sa.Column('file_meta', sa.Text(), nullable=True),
    sa.Column('source_classification', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['verification_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyzed_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyzed_contents_job_id'), ['job_id'], unique=False)

    op.create_table('evidence_edges',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('edge_type', sa.String(length=24), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_key', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['verification_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'source_key', 'edge_type', 'target_key', name='uq_edge')
    )
    with op.batch_alter_table('evidence_edges', schema=None) as batch_op:
        batch_op.create_index('ix_edges_job', ['job_id', 'source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_edges_job_id'), ['job_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurred_at_raw', sa.String(length=128), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('event_kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['verification_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_timeline_job_time', ['job_id', 'occurred_at'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('content_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=24), nullable=False),
    sa.Column('checkable', sa.Boolean(), nullable=False),
    sa.Column('claim_confidence', sa.Float(), nullable=False),
    sa.Column('time_context', sa.String(length=255), nullable=True),
    sa.Column('entities', sa.Text(), nullable=True),
    sa.Column('numbers', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['analyzed_contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['verification_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'ordinal', name='uq_claims_job_ordinal')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_content_id'), ['content_id'], unique=False)
        batch_op.create_index('ix_claims_job', ['job_id', 'ordinal'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_job_id'), ['job_id'], unique=False)

    op.create_table('media_analyses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('content_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('media_type', sa.String(length=24), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('manipulation_risk', sa.Float(), nullable=True),
    sa.Column('ai_generation_signal', sa.Float(), nullable=True),
    sa.Column('ai_signal_confidence', sa.String(length=16), nullable=True),
    sa.Column('authenticity_note', sa.Text(), nullable=True),
    sa.Column('detectors_run', sa.Text(), nullable=True),
    sa.Column('source_classification', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['analyzed_contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['verification_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_analyses_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_analyses_job_id'), ['job_id'], unique=False)

    op.create_table('claim_verdicts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_rationale', sa.Text(), nullable=True),
    sa.Column('supporting_count', sa.Integer(), nullable=False),
    sa.Column('contradicting_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('primary_source_available', sa.Boolean(), nullable=False),
    sa.Column('temporal_flag', sa.String(length=32), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('fused_signals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_verdicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_verdicts_claim_id'), ['claim_id'], unique=True)

    op.create_table('evidence_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('claim_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('stance_confidence', sa.Float(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('source_classification', sa.String(length=32), nullable=False),
    sa.Column('independence_cluster', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['verification_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_items_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_items_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_evidence_job_claim', ['job_id', 'claim_id'], unique=False)

    op.create_table('fact_check_matches',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('claim_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=True),
    sa.Column('textual_rating', sa.String(length=128), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('review_snippet', sa.Text(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('source_classification', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['verification_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fact_check_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_check_matches_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_check_matches_job_id'), ['job_id'], unique=False)

    op.create_table('numerical_checks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('claim_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('check_type', sa.String(length=48), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('expected', sa.String(length=128), nullable=True),
    sa.Column('observed', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('source_classification', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['verification_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('numerical_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_numerical_checks_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_numerical_checks_job_id'), ['job_id'], unique=False)

    with op.batch_alter_table('feature_snapshots', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('intervention_scores', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('misinformation_scores', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('propagation_events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propagation_events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('misinformation_scores', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('intervention_scores', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('feature_snapshots', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('numerical_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_numerical_checks_job_id'))
        batch_op.drop_index(batch_op.f('ix_numerical_checks_claim_id'))

    op.drop_table('numerical_checks')
    with op.batch_alter_table('fact_check_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_check_matches_job_id'))
        batch_op.drop_index(batch_op.f('ix_fact_check_matches_claim_id'))

    op.drop_table('fact_check_matches')
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_job_claim')
        batch_op.drop_index(batch_op.f('ix_evidence_items_job_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_items_claim_id'))

    op.drop_table('evidence_items')
    with op.batch_alter_table('claim_verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_verdicts_claim_id'))

    op.drop_table('claim_verdicts')
    with op.batch_alter_table('media_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_analyses_job_id'))
        batch_op.drop_index(batch_op.f('ix_media_analyses_content_id'))

    op.drop_table('media_analyses')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_job_id'))
        batch_op.drop_index('ix_claims_job')
        batch_op.drop_index(batch_op.f('ix_claims_content_id'))

    op.drop_table('claims')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index('ix_timeline_job_time')
        batch_op.drop_index(batch_op.f('ix_timeline_events_job_id'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('evidence_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_edges_job_id'))
        batch_op.drop_index('ix_edges_job')

    op.drop_table('evidence_edges')
    with op.batch_alter_table('analyzed_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyzed_contents_job_id'))

    op.drop_table('analyzed_contents')
    with op.batch_alter_table('verification_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_vjobs_status_created')
        batch_op.drop_index(batch_op.f('ix_verification_jobs_status'))

    op.drop_table('verification_jobs')
    with op.batch_alter_table('source_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_profiles_host'))

    op.drop_table('source_profiles')
    # ### end Alembic commands ###
