"""initial schema

Revision ID: 84ad8293d066
Revises: 
Create Date: 2026-09-02 06:02:02.909526
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '84ad8293d066'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_successful_fetch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('rate_limit_status', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_source_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_source_status_platform'), ['platform'], unique=True)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.String(length=255), nullable=False),
    sa.Column('author_display_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_post_id', name='uq_posts_platform_external_id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_platform'), ['platform'], unique=False)
        batch_op.create_index('ix_posts_platform_posted_at', ['platform', 'posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_posted_at'), ['posted_at'], unique=False)

    op.create_table('feature_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('share_velocity', sa.Float(), nullable=True),
    sa.Column('share_velocity_5m', sa.Float(), nullable=True),
    sa.Column('share_velocity_15m', sa.Float(), nullable=True),
    sa.Column('share_acceleration', sa.Float(), nullable=True),
    sa.Column('engagement_velocity', sa.Float(), nullable=True),
    sa.Column('engagement_acceleration', sa.Float(), nullable=True),
    sa.Column('view_velocity', sa.Float(), nullable=True),
    sa.Column('comment_velocity', sa.Float(), nullable=True),
    sa.Column('like_velocity', sa.Float(), nullable=True),
    sa.Column('unique_sharers', sa.Integer(), nullable=True),
    sa.Column('new_unique_sharers', sa.Float(), nullable=True),
    sa.Column('unique_sharer_growth_rate', sa.Float(), nullable=True),
    sa.Column('propagation_depth', sa.Float(), nullable=True),
    sa.Column('propagation_breadth', sa.Float(), nullable=True),
    sa.Column('cascade_size', sa.Integer(), nullable=True),
    sa.Column('branching_factor', sa.Float(), nullable=True),
    sa.Column('avg_time_between_shares', sa.Float(), nullable=True),
    sa.Column('median_time_between_shares', sa.Float(), nullable=True),
    sa.Column('network_growth_rate', sa.Float(), nullable=True),
    sa.Column('reshare_concentration', sa.Float(), nullable=True),
    sa.Column('time_since_post', sa.Float(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('minute_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('author_followers', sa.Integer(), nullable=True),
    sa.Column('engagement_ratio', sa.Float(), nullable=True),
    sa.Column('shares_to_views_ratio', sa.Float(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('capital_ratio', sa.Float(), nullable=True),
    sa.Column('exclamation_count', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('url_present', sa.Boolean(), nullable=True),
    sa.Column('hashtag_count', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('emotional_intensity', sa.Float(), nullable=True),
    sa.Column('sensational_score', sa.Float(), nullable=True),
    sa.Column('claim_score', sa.Float(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'timestamp', name='uq_feature_snapshot_post_ts')
    )
    with op.batch_alter_table('feature_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_snapshots_post_id'), ['post_id'], unique=False)
        batch_op.create_index('ix_feature_snapshots_post_ts', ['post_id', 'timestamp'], unique=False)

    op.create_table('intervention_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spread_score', sa.Float(), nullable=False),
    sa.Column('misinformation_score', sa.Float(), nullable=False),
    sa.Column('intervention_priority', sa.Float(), nullable=False),
    sa.Column('priority_label', sa.String(length=16), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('top_factors', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intervention_scores', schema=None) as batch_op:
        batch_op.create_index('ix_intervention_post_ts', ['post_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_intervention_priority', ['intervention_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_intervention_scores_post_id'), ['post_id'], unique=False)

    op.create_table('metric_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('unique_sharers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'timestamp', name='uq_metric_snapshot_post_ts')
    )
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_snapshots_post_id'), ['post_id'], unique=False)
        batch_op.create_index('ix_metric_snapshots_post_ts', ['post_id', 'timestamp'], unique=False)

    op.create_table('misinformation_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_label', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('misinformation_scores', schema=None) as batch_op:
        batch_op.create_index('ix_misinfo_post_ts', ['post_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_misinformation_scores_post_id'), ['post_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('predicted_additional_shares', sa.Float(), nullable=False),
    sa.Column('predicted_total_shares', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prediction_type', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_horizon_minutes'), ['horizon_minutes'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_post_id'), ['post_id'], unique=False)
        batch_op.create_index('ix_predictions_post_ts_horizon', ['post_id', 'prediction_timestamp', 'horizon_minutes'], unique=False)

    op.create_table('propagation_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('source_user_id', sa.String(length=255), nullable=True),
    sa.Column('target_user_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_since_original_post', sa.Float(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('propagation_events', schema=None) as batch_op:
        batch_op.create_index('ix_propagation_events_post_depth', ['post_id', 'depth'], unique=False)
        batch_op.create_index(batch_op.f('ix_propagation_events_post_id'), ['post_id'], unique=False)
        batch_op.create_index('ix_propagation_events_post_ts', ['post_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propagation_events', schema=None) as batch_op:
        batch_op.drop_index('ix_propagation_events_post_ts')
        batch_op.drop_index(batch_op.f('ix_propagation_events_post_id'))
        batch_op.drop_index('ix_propagation_events_post_depth')

    op.drop_table('propagation_events')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_predictions_post_ts_horizon')
        batch_op.drop_index(batch_op.f('ix_predictions_post_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_horizon_minutes'))

    op.drop_table('predictions')
    with op.batch_alter_table('misinformation_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misinformation_scores_post_id'))
        batch_op.drop_index('ix_misinfo_post_ts')

    op.drop_table('misinformation_scores')
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_metric_snapshots_post_ts')
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_post_id'))

    op.drop_table('metric_snapshots')
    with op.batch_alter_table('intervention_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intervention_scores_post_id'))
        batch_op.drop_index('ix_intervention_priority')
        batch_op.drop_index('ix_intervention_post_ts')

    op.drop_table('intervention_scores')
    with op.batch_alter_table('feature_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_feature_snapshots_post_ts')
        batch_op.drop_index(batch_op.f('ix_feature_snapshots_post_id'))

    op.drop_table('feature_snapshots')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_posted_at'))
        batch_op.drop_index('ix_posts_platform_posted_at')
        batch_op.drop_index(batch_op.f('ix_posts_platform'))

    op.drop_table('posts')
    with op.batch_alter_table('data_source_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_source_status_platform'))

    op.drop_table('data_source_status')
    # ### end Alembic commands ###
